---
title: Allez Pilates
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: false
    comments: false
    share: false
    related: false
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: false
og_image: "/assets/images/og-site-logo.png"
repository: bfulkers/allez-minimal
social:
  type: Organization
  name: Allez Pilates
  links:
  - https://www.facebook.com/allezpilates
  - https://www.instagram.com/allezpilates
masthead_title: ''
logo: "/assets/images/masthead-logo.png"
email: 
description: Allez Pilates offers exercise programs based on anatomy and biomechanics
  knowledge that deliver real results through a safe and effective framework.
minimal_mistakes_skin: allez
search: false
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.19.2
permalink: "/:title/"
paginate: 5
paginate_path: "/page:num/"
include:
- _pages
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
author:
  name: Camelia Khalid
  avatar: "/assets/images/bio-photo.jpg"
  bio: I offer exercise programs based on anatomy and biomechanics knowledge which
    deliver real results through a safe and effective framework.
  links:
  - label: Facebook
    icon: fab fa-fw fa-twitter-square
    url: https://facebook.com/allezpilates
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: https://instagram.com/allezpilates
footer:
  links:
  - label: Facebook
    icon: fab fa-fw fa-facebook
    url: https://facebook.com/allezpilates
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: https://instagram.com/allezpilates
